### ISSUE TITLE
Apparent allele detection bug

### ISSUE THREAD

**Issue by scharch** [psathyrella/partis#205]
```
root@bdd2e90fec3e:/partis# ./bin/partis cache-parameters --infname /host/ifs/scratch/c2b2/ls_nih/cs3037/spectrum/08248/08248_kappa/output/sequences/nucleotide/08248_kappa_noFrameshifts.fa --find-new-alleles --n-procs 4 --new-allele-fname /host/ifs/scratch/c2b2/ls_nih/cs3037/spectrum/partis/kappa/newPartis.fa --chain k
  using default parameter dir '_output/_host_ifs_scratch_c2b2_ls_nih_cs3037_spectrum_08248_08248_kappa_output_sequences_nucleotide_08248_kappa_noFrameshifts'
caching parameters
NOTE if args.generate_new_alignment is set, only removes original allele if a new allele is found -- it doesn't remove other genes (which may be what we want -- they get in effect removed later when we only write yamels for genes that we actually saw)
smith-waterman   (looking for new alleles)
Traceback (most recent call last):
  File "./bin/partis", line 387, in <module>
    args.func(args)
  File "./bin/partis", line 142, in run_partitiondriver
    parter.cache_parameters()
  File "/partis/python/partitiondriver.py", line 213, in cache_parameters
    self.find_new_alleles()
  File "/partis/python/partitiondriver.py", line 172, in find_new_alleles
    self.run_waterer(find_new_alleles=True)
  File "/partis/python/partitiondriver.py", line 160, in run_waterer
    waterer.run(cachefname)
  File "/partis/python/waterer.py", line 80, in run
    self.read_output(base_outfname, n_procs)
  File "/partis/python/waterer.py", line 290, in read_output
    self.summarize_query(qinfo, queries_to_rerun)  # returns before adding to <self.info> if it thinks we should rerun the query
  File "/partis/python/waterer.py", line 744, in summarize_query
    self.add_to_info(qinfo, best, codon_positions)
  File "/partis/python/waterer.py", line 628, in add_to_info
    self.alfinder.increment(self.info[qname])
  File "/partis/python/allelefinder.py", line 57, in increment
    self.mfreqer.increment(info)
TypeError: increment() takes exactly 3 arguments (2 given)
```

I get the same error with a lambda set, but a heavy chain set works ok. FWIW, I was able to run an older version of partis on both light chain datasets by hacking my own custom germline set.

EDIT: spoke too soon - I got the same error for the heavy chain set, too.

**Comment by psathyrella** [comment]
heh, don't worry, it's more than apparent...

Thanks for catching it, I just pushed a fix to master (docker hub will take a few minutes to build it).

**Comment by psathyrella** [comment]
docker hub finally finished the build... the previous one failed, as they sometimes do, because of timeout issues or some such between the docker hub and ubuntu/debian servers.
