### ISSUE TITLE
Header name error

### ISSUE THREAD

**Issue by Irrationone** [psathyrella/partis#213]
Received this error today:

```
/bin/sh: line 1: 23854 Aborted                 (core dumped) /shahlab/azhang/projects/ITH_Immune/software/partis/packages/ham/bcrham --algorithm viterbi --hmmdir /shahlab/azhang/pipeline_outputs/ith_immune/partis/run2/16216987/parameters/sw/hmms --datadir /tmp/alzhang/hmms/692817/germline-sets --infile /tmp/alzhang/hmms/692817/hmm_input.csv --outfile /tmp/alzhang/hmms/692817/hmm_output.csv --chain h --random-seed 1474002811 --ambig-base N > /tmp/alzhang/hmms/692817/out 2> /tmp/alzhang/hmms/692817/err
Traceback (most recent call last):
  File "./bin/partis.py", line 488, in <module>
    args.func(args)
  File "./bin/partis.py", line 213, in run_partitiondriver
    _ = check_maybe_auto_cache_parameters(args, gldir)
  File "./bin/partis.py", line 37, in check_maybe_auto_cache_parameters
    parter.cache_parameters()
  File "/shahlab/azhang/projects/ITH_Immune/software/partis/python/partitiondriver.py", line 254, in cache_parameters
    self.run_hmm('viterbi', parameter_in_dir=self.sw_param_dir, parameter_out_dir=self.hmm_param_dir, count_parameters=True)
  File "/shahlab/azhang/projects/ITH_Immune/software/partis/python/partitiondriver.py", line 677, in run_hmm
    self.execute(cmd_str, n_procs)
  File "/shahlab/azhang/projects/ITH_Immune/software/partis/python/partitiondriver.py", line 649, in execute
    utils.run_cmds(cmdfos, debug='print' if (self.args.debug or self.current_action=='partition') else None)
  File "/shahlab/azhang/projects/ITH_Immune/software/partis/python/utils.py", line 1550, in run_cmds
    finish_process(iproc, procs, n_tries, cmdfos[iproc]['workdir'], cmdfos[iproc]['logdir'], cmdfos[iproc]['outfname'], cmdfos[iproc]['cmd_str'], dbgfo=cmdfos[iproc]['dbgfo'], debug=debug)
  File "/shahlab/azhang/projects/ITH_Immune/software/partis/python/utils.py", line 1558, in finish_process
    process_out_err('', '', extra_str='' if len(procs) == 1 else str(iproc), dbgfo=dbgfo, logdir=logdir, debug=debug)
  File "/shahlab/azhang/projects/ITH_Immune/software/partis/python/utils.py", line 1604, in process_out_err
    raise Exception('couldn\'t find \'%s\' line in:\nstdout:\n%s\nstderr:\n%s' % (header, out, err))
Exception: couldn't find 'calcd' line in:
stdout:

stderr:
terminate called after throwing an instance of 'std::runtime_error'
  what():  args.cc: found unexpected header mut_freq' in input file /tmp/alzhang/hmms/692817/hmm_input.csv
```

Occurs on my test case as well. Figure it's just some minor typo.

**Comment by psathyrella** [comment]
hm, my tests ran ok. Any chance you didn't recompile?

**Comment by Irrationone** [comment]
Ugh, sorry. That's exactly it, thanks!

**Comment by psathyrella** [comment]
I only recognize the error so quickly because I've done that exact thing so many times...
