### ISSUE TITLE
ig-sw binary d.n.e

### ISSUE THREAD

**Issue by ecudone** [psathyrella/partis#241]
Ran this annotation query, but ran into an issue where it seems a file, "ig-sw binary" does not exis.
I uninsulated and reinstalled for sanity sake and got the same issue. I looked through the files and couldn't find any /partis/packages/ig-sw/src/ig_align/ig-sw file, so it appears to be missing.

root@5884105ead26:/partis# ./bin/partis annotate --infname /host/NE2_3.fa --outfname /host/NE2_3_annotated.csv

caching parameters
      vsearch: 3658 v annotations in 0.3 sec
    keeping 60 / 239 v genes
smith-waterman 
Traceback (most recent call last):
  File "./bin/partis", line 597, in <module>
    args.func(args)
  File "./bin/partis", line 185, in run_partitiondriver
    parter.cache_parameters()
  File "/partis/python/partitiondriver.py", line 247, in cache_parameters
    self.run_waterer()
  File "/partis/python/partitiondriver.py", line 153, in run_waterer
    simglfo=self.simglfo, duplicates=self.duplicates, pre_failed_queries=pre_failed_queries, aligned_gl_seqs=self.aligned_gl_seqs)
  File "/partis/python/waterer.py", line 74, in __init__
    **raise Exception('ig-sw binary d.n.e: %s' % self.args.ig_sw_binary)
Exception: ig-sw binary d.n.e: /partis/packages/ig-sw/src/ig_align/ig-sw
Traceback (most recent call last):
  File "./bin/partis", line 597, in <module>
    args.func(args)
  File "./bin/partis", line 198, in run_partitiondriver
    check_call(newargv)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['./bin/partis', 'cache-parameters', '--infname', '/host/NE2_3.fa', '--outfname', '/host/NE2_3_annotated.csv']' returned non-zero exit status 1**

**Comment by psathyrella** [comment]
hm, did you compile by running ./bin/build.sh first?
