### ISSUE TITLE
Exceeded max number of tries for cmd

### ISSUE THREAD

**Issue by NikaAb** [psathyrella/partis#286]
Dear Duncan,

I have some fasta files from CLL patients.I wanted to see the partition results and Partis analyzed all of them perfectly except one of them. This is the last part of what I get as the output for this particular fasta file :

```
exceeded max number of tries for cmd
    /partis/packages/ham/bcrham --algorithm forward --hmmdir /partis/bin/_output/_host_home_davi_Bureau_Fastq_PSL_Merged_seq_Patient_seven_P7/hmm/hmms --datadir /tmp/partis-work/hmms/172528/germline-sets --infile /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_input.csv --outfile /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_output.csv --locus igh --random-seed 1555420417 --only-cache-new-vals --input-cachefname /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_cached_info.csv --output-cachefname /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_cached_info.csv --partition --max-logprob-drop 5.0 --hamming-fraction-bound-lo 0.015 --hamming-fraction-bound-hi 0.0647084853712 --logprob-ratio-threshold 18.0 --biggest-naive-seq-cluster-to-calculate 15 --biggest-logprob-cluster-to-calculate 15 --n-partitions-to-write 10 --ambig-base N
look for output in /tmp/partis-work/hmms/172528/istep-0/hmm-7 and /tmp/partis-work/hmms/172528/istep-0/hmm-7
Traceback (most recent call last):
  File "./partis", line 459, in <module>
    args.func(args)
  File "./partis", line 215, in run_partitiondriver
    parter.run(actions)
  File "/partis/python/partitiondriver.py", line 108, in run
    self.action_fcns[tmpaction]()
  File "/partis/python/partitiondriver.py", line 469, in partition
    cpath = self.cluster_with_bcrham()
  File "/partis/python/partitiondriver.py", line 705, in cluster_with_bcrham
    cpath, _, _ = self.run_hmm('forward', self.sub_param_dir, n_procs=n_procs, partition=cpath.partitions[cpath.i_best_minus_x], shuffle_input=True)  # note that this annihilates the old <cpath>, which is a memory optimization (but we write all of them to the cpath progress dir)
  File "/partis/python/partitiondriver.py", line 1073, in run_hmm
    self.execute(cmd_str, n_procs)
  File "/partis/python/partitiondriver.py", line 1044, in execute
    utils.run_cmds(cmdfos, batch_system=self.args.batch_system, batch_options=self.args.batch_options, batch_config_fname=self.args.batch_config_fname, debug='print' if self.args.debug else None)
  File "/partis/python/utils.py", line 2614, in run_cmds
    finish_process(iproc, procs, n_tries, cmdfos[iproc], n_max_tries, dbgfo=cmdfos[iproc]['dbgfo'], batch_system=batch_system, batch_options=batch_options, debug=debug, ignore_stderr=ignore_stderr, clean_on_success=clean_on_success, shell=shell)
  File "/partis/python/utils.py", line 2709, in finish_process
    raise Exception(failstr)
Exception: exceeded max number of tries for cmd
    /partis/packages/ham/bcrham --algorithm forward --hmmdir /partis/bin/_output/_host_home_davi_Bureau_Fastq_PSL_Merged_seq_Patient_seven_P7/hmm/hmms --datadir /tmp/partis-work/hmms/172528/germline-sets --infile /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_input.csv --outfile /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_output.csv --locus igh --random-seed 1555420417 --only-cache-new-vals --input-cachefname /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_cached_info.csv --output-cachefname /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_cached_info.csv --partition --max-logprob-drop 5.0 --hamming-fraction-bound-lo 0.015 --hamming-fraction-bound-hi 0.0647084853712 --logprob-ratio-threshold 18.0 --biggest-naive-seq-cluster-to-calculate 15 --biggest-logprob-cluster-to-calculate 15 --n-partitions-to-write 10 --ambig-base N
look for output in /tmp/partis-work/hmms/172528/istep-0/hmm-7 and /tmp/partis-work/hmms/172528/istep-0/hmm-7
```

Do you know where this probleme come's from? I see that  there are some output files written, are they correct considering this error?
Thanks a lot for your help!
Nika

**Comment by psathyrella** [comment]
I can't be sure based on that -- you need to either look in the directory it lists (`/tmp/partis-work/hmms/172528/istep-0/hmm-7`) for the stdout/stderr files (I think named `out` and `err`) from the command that failed, or else run the command that failed, on the second to last line:

```
/partis/packages/ham/bcrham --algorithm forward --hmmdir /partis/bin/_output/_host_home_davi_Bureau_Fastq_PSL_Merged_seq_Patient_seven_P7/hmm/hmms --datadir /tmp/partis-work/hmms/172528/germline-sets --infile /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_input.csv --outfile /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_output.csv --locus igh --random-seed 1555420417 --only-cache-new-vals --input-cachefname /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_cached_info.csv --output-cachefname /tmp/partis-work/hmms/172528/istep-0/hmm-7/hmm_cached_info.csv --partition --max-logprob-drop 5.0 --hamming-fraction-bound-lo 0.015 --hamming-fraction-bound-hi 0.0647084853712 --logprob-ratio-threshold 18.0 --biggest-naive-seq-cluster-to-calculate 15 --biggest-logprob-cluster-to-calculate 15 --n-partitions-to-write 10 --ambig-base N
```
to get stdout and stderr printed to terminal.

(note, i ninja edited your text to swap single ` for triple ```)

**Comment by psathyrella** [comment]
I'm going to assume you fixed this? If not feel free to reopen.
